---
- name: Access S3 bucket list in AWS using roles
  hosts: all
  collections:
    - amazon.aws
  
  tasks:
    - name: Testing that were started
      ansible.builtin.debug:
        msg: "Here we go..."
        
    - name: Check token stuff
      ansible.builtin.debug:
        msg: "Secret Key: { credentials['SecretAccessKey'] }   Access: { credentials['AccessKeyId'] }    Token: { credentials['SessionToken']}"

    - name: Get S3 bucket info
      amazon.aws.s3_bucket_info:
      register: result

    - name: Dump bucket info
      ansible.builtin.debug:
        var: result
