---
- name: Access S3 bucket list in AWS using roles
  hosts: all
  collections:
    - amazon.aws
  
  tasks:
    - name: Testing that were started
      ansible.builtin.debug:
        msg: "Here we go..."
        
    - name: Check token stuff
      ansible.builtin.debug:
        msg: "Secret Key: {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}   Access: {{ lookup('env', 'AWS_ACCESS_KEY_ID') }}    Token: {{ lookup('env', 'AWS_SESSION_TOKEN') }}    Token: {{ lookup('env', 'AWS_SECURITY_TOKEN') }}"

    - name: Get S3 bucket info aaa
      amazon.aws.s3_bucket_info:
        access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        session_token: "{{ lookup('env', 'AWS_SECURITY_TOKEN') }}"
      register: result_easy

    - name: Dump bucket info aaa
      ansible.builtin.debug:
        var: result_easy

    - name: Get S3 bucket info
      amazon.aws.s3_bucket_info:
      register: result

    - name: Dump bucket info
      ansible.builtin.debug:
        var: result
